#+STARTUP: overview indent

* Linux TFS development environment
There's a Makefile that will git clone the needed repos.

** Usage Notes
*** Launching a "Host <-> Router <-> Router <-> Host" setup.
You can use the tests to bring up a working iptfs ipsec tunnel. You'll need to
have installed ~qemu~, ~socat~, ~python~ and optional but highly recommended
~tmux~, additionally you'll need to install the python requirements,

#+begin_src bash
  python3 -m venv venv
  source venv/bin/activate
  pip install -r python-requirements.txt
#+end_src

Then run a test adding the `--pause` flag, and it will pause before running the first
test, but after having configured the hosts (h1, h2) and routers (r1, r2).

NOTE: If your `sudo` command forces a restricted PATH (~secure_path~) then the
python virtual environment may not work. In this case `sudo bash` and then
activate the virtual environment as root.

NOTE: SUDO: For best results add the following to your ~/etc/sudoers~ config.
This will allow tmux to continue to work inside the sudo environment.

#+begin_src shell
  Defaults env_keep += "TMUX"
  Defaults env_keep += "TMUX_PANE"
#+end_src

#+begin_src shell
  $ sudo -E pytest -s -v tests/simplenet --pause
  [...]
  == PAUSING: before test 'tests/simplenet/test_simplenet.py::test_net_up' ==
#+end_src

or

#+begin_src shell
  $ sudo -E bash
  # tmux # optional but highly useful
  # source venv/bin/activate
  # pytest -s -v tests/simplenet --pause
  [...]
  == PAUSING: before test 'tests/simplenet/test_simplenet.py::test_net_up' ==
#+end_src


You can now log into the running setup in another terminal. Use ~socat~ to log
into the console of the running qemu'd linux.

#+begin_src shell
  $ sudo socat /dev/stdin,rawer,escape=0x1d,,echo=0,icanon=0 \
      unix-connect:/tmp/unet-test/tests.simplenet.test_simplenet/r1/s/console2
#+end_src

You can use ~mucmd~ to simply enter the namespace of the running node (e.g., to
ping from ~h1~ to ~h2~ over the iptfs tunnel use the following command).

#+begin_src shell
  $ sudo mucmd -d /tmp/unet-test/tests.simplenet.test_simplenet h1 ping 10.0.2.4
  PING 10.0.2.4 (10.0.2.4) 56(84) bytes of data.
  64 bytes from 10.0.2.4: icmp_seq=1 ttl=62 time=1.22 ms
  64 bytes from 10.0.2.4: icmp_seq=2 ttl=62 time=1.40 ms
  64 bytes from 10.0.2.4: icmp_seq=3 ttl=62 time=1.25 ms
  ...
#+end_src

*** Qemu
**** consoles
2 serial consoles are created using unix sockets '/tmp/qemu-sock/console' and
'/tmp/qemu-sock/con2'. These can be accessed in the namespace with the following
command:

~socat /dev/stdin,escape=0x1d,rawer unix-connect:/tmp/qemu-sock/console~

And outside of the namespace with

~socat /dev/stdin,escape=0x1d,rawer unix-connect:<rundir>/<name>/s/console~

Where ~<rundir>~ is usually ~/tmp/unet-root/~, so if the node name is ~r1~:

~sudo socat /dev/stdin,rawer,escape=0x1d,,echo=0,icanon=0 unix-connect:/tmp/unet-root/r1/console~

If your ~socat~ doesn't support ~rawer~ option replace with ~raw,echo=0,icanon=0~.
**** GDB
#+begin_src bash
  $ sudo gdb linux/vmlinux
  (gdb) target remote /tmp/unet-root/r1/s/gdbserver
  ...

  or
  (gdb)
  target remote /tmp/unet-test/tests.simplenet.test_simplenet/r1/s/gdbserver
  target remote /tmp/unet-test/tests.simplenet.test_simplenet/r2/s/gdbserver

  target remote /tmp/unet-test/tests.errors.test_errors/r1/s/gdbserver
  target remote /tmp/unet-test/tests.errors.test_errors/r2/s/gdbserver

  target remote /tmp/unet-test/tests.phynic.test_simplenet/r1/s/gdbserver

  target remote /tmp/unet-test/tests.stress.test_stress/r2/s/gdbserver

  target remote /tmp/unet-test/tests.utpkt.test_utpkt/r1/s/gdbserver

  target remote /tmp/unet-test/tests.verify.test_verify/r1/s/gdbserver

#+end_src

** Building/Editing Notes
*** CCLS
I like to use ccls with LSP mode in emacs, which will allow you to jump to all
references with semantics (i.e., it's not just a tag search) as well as
displaying documentation and tab completion of symbols etc..

In order for this to work seemlessly you need to do 2 things:

  1. run `scripts/clang-tools/gen_compile_commands.py`
  2. printf "%compile_commands.json\n-D__IN_CCLS__\n" > .ccls

#2 isn't technically needed but I have conditionally wrapped a few couple low
level `asm` things on __IN_CCLS__ in the iptfs branch to keep WARN/BUG macros
from being highlighted as "bad code".

** Design Notes
*** Config
The most basic configuration is to select "iptfs" as the mode rather than
"tunnel" when configuring an IPsec SA.

Additionally there are further configuration options based on the mode the iptfs
tunnel should run in.

**** common configuration
- iptfs-dont-fragment :: boolean to disable fragmenting inner packets, defaults to false
- iptfs-max-queue-size :: The maximum queue size for pending packets to send.
- iptfs-pkt-size :: the size of the outer packet (outer ip, esp, iptfs, + inner ip
  packets), either a value or auto to use PMTU
- iptfs-reorder-window-size :: The number of packets to hold waiting for re-ordered
  packets to arrive before considering those missing packets dropped. Default
  for fixed-rate send is 1. Default for demand-rate is 3. If the other endpoint
  is in dont-fragment mode then this value can be set to 0.
- iptfs-drop-time :: The number microseconds to wait unti considering
  the next in sequence packet as lost.

**** fixed-rate fixed-sized configuration 

- iptfs-fixed-rate :: a fixed rate to send outer packets
- iptfs-inner-fixed-rate :: alternate form of fixed rate to sepcify inner packets datarate
- iptfs-max-delay :: alternate config for max-queue-size, which is based on the fixed send rate.
- iptfs-disable-congestion-control :: disble congestion control, should only be used
  when the user is in full administrative control of all paths the tunnel may take.
- iptfs-no-pad-only :: dont' send all pad packets (debug option)

**** demand-rate configuration 
- iptfs-initial-delay :: amount of time in microseconds to wait after before servicing
  the output queue when the initial packet arrives (first in queue). This time
  allows for collecting more packets to take advantage of IPTFS packet aggregation.


*** From Steffen's Mail
[...] look at:

net/xfrm/*
net/ipv4/xfrm*
net/ipv4/esp4*
net/ipv6/xfrm*
net/ipv6/esp6*

> Anything else you think might be useful too would be much appreciated of course.

I think TFS should be a new encapsulation mode. We currently have
tunnel, transport and beet mode (and some odd ipv6 modes). Adding
a tfs_tunnel mode to add all the TFS special stuff would be the
way to go at a first glance. The modes are implemented in:

net/xfrm/xfrm_output.c
net/xfrm/xfrm_input.c


** Bugs
- xfrmi_rcv_cb is looking up xfrm_state from our newly created skb from decaping
  iptfs, but it has not xfrm_state so we panic
  - Need to associate the xfrm_state with new skbs too.. is there a refcnt for this?


* Sandbox

** Sample PPS and packet send times for 1500B IP packets
#+begin_src C :includes <stdio.h> :includes <stdint.h>
#include <stdio.h>
#define ENET_OHEAD (14 + 4 + 8 + 12)
#define _1GE_PPS(iptfs_ip_mtu) ((1e9 / 8) / ((iptfs_ip_mtu) + ENET_OHEAD))
#define _10GE_PPS(iptfs_ip_mtu) ((1e10 / 8) / ((iptfs_ip_mtu) + ENET_OHEAD))
#define _40GE_PPS(iptfs_ip_mtu) ((4e10 / 8) / ((iptfs_ip_mtu) + ENET_OHEAD))
#define _100GE_PPS(iptfs_ip_mtu) ((1e11 / 8) / ((iptfs_ip_mtu) + ENET_OHEAD))
#define _1GE_PP_NANOS(iptfs_ip_mtu) (1e9 / _1GE_PPS(iptfs_ip_mtu))
#define _10GE_PP_NANOS(iptfs_ip_mtu) (1e9 / _10GE_PPS(iptfs_ip_mtu))
#define _40GE_PP_NANOS(iptfs_ip_mtu) (1e9 / _40GE_PPS(iptfs_ip_mtu))
#define _100GE_PP_NANOS(iptfs_ip_mtu) (1e9 / _100GE_PPS(iptfs_ip_mtu))

int mtu = 64;

printf("+ 1GE 10GE 40GE 100GE\n");
printf("PPS %lu %lu %lu %lu\n", (uint64_t)_1GE_PPS(mtu),(uint64_t)_10GE_PPS(mtu),(uint64_t)_40GE_PPS(mtu),(uint64_t)_100GE_PPS(mtu));
printf("packet-time %luns %luns %luns %luns\n", (uint64_t)_1GE_PP_NANOS(mtu),(uint64_t)_10GE_PP_NANOS(mtu),(uint64_t)_40GE_PP_NANOS(mtu),(uint64_t)_100GE_PP_NANOS(mtu));
#+end_src

#+RESULTS:
| +           | 1GE     | 10GE     | 40GE     | 100GE     |
| PPS         | 1225490 | 12254901 | 49019607 | 122549019 |
| packet-time | 816ns   | 81ns     | 20ns     | 8ns       |


** Performance Triaging
Testing done on a single server with 3 networks cards using munet and wiring the
ports to each other. Performance is nowhere near line rate even for routed packets.
[h1] - [r1] - [r2] - [h2]
       ===========

*** Qemu emulated - single socket/core
- Routed from h1 to h2 iperf bidir:              ~2000 Mbps
- IPsec [r1,r2] tunnel, from h1 to h2 iperf bidir ~120 Mbps
- IPTFS [r1,r2] tunnel, from h1 to h2 iperf bidir   ~2 Mbps
*** Qemu -accel kvm - single socket/core
- Routed from h1 to h2 iperf bidir:              ~9400 Mbps
- IPsec [r1,r2] tunnel, from h1 to h2 iperf bidir ~920 Mbps
- IPTFS [r1,r2] tunnel, from h1 to h2 iperf bidir   ~2 Mbps
*** Qemu -accel kvm - 4 sockets
- Routed from h1 to h2 iperf bidir:               ~9400 Mbps
- IPsec [r1,r2] tunnel, from h1 to h2 iperf bidir ~7200 Mbps
- IPTFS [r1,r2] tunnel, from h1 to h2 iperf bidir     700Kbps-3.87Mbps

  
* Examples
** These are single Core
*** tests/stress/trex_stress_phy.py::test_policy_imix
**** mode == tunnel (i.e., normal ipsec) (50%/50%)
Global Statistics

connection   : localhost, Port 4501                       total_tx_L2  : 3.83 Gbps
version      : STL @ v2.98                                total_tx_L1  : 3.93 Gbps
cpu_util.    : 6.52% @ 2 cores (2 per dual port)          total_rx     : 3.04 Gbps
rx_cpu_util. : 8.26% / 0 pps                              total_pps    : 645.97 Kpps
async_util.  : 0% / 30.41 bps                             drop_rate    : 792.36 Mbps
total_cps.   : 0 cps                                      queue_full   : 0 pkts

Port Statistics

   port    |         0         |         1         |       total
-----------+-------------------+-------------------+------------------
owner      |              root |              root |
link       |                UP |                UP |
state      |      TRANSMITTING |      TRANSMITTING |
speed      |           40 Gb/s |           40 Gb/s |
CPU util.  |             6.52% |             6.52% |
--         |                   |                   |
Tx bps L2  |         1.92 Gbps |         1.91 Gbps |         3.83 Gbps
Tx bps L1  |         1.97 Gbps |         1.96 Gbps |         3.93 Gbps
Tx pps     |       323.81 Kpps |       322.16 Kpps |       645.97 Kpps
Line Util. |            4.93 % |             4.9 % |
---        |                   |                   |
Rx bps     |         1.52 Gbps |         1.51 Gbps |         3.04 Gbps
Rx pps     |       256.81 Kpps |        255.5 Kpps |       512.31 Kpps
----       |                   |                   |
opackets   |           7479318 |           7511222 |          14990540
ipackets   |           5941015 |           5965888 |          11906903
obytes     |        5542174638 |        5565815502 |       11107990140
ibytes     |        4402286022 |        4421020888 |        8823306910
tx-pkts    |        7.48 Mpkts |        7.51 Mpkts |       14.99 Mpkts
rx-pkts    |        5.94 Mpkts |        5.97 Mpkts |       11.91 Mpkts
tx-bytes   |           5.54 GB |           5.57 GB |          11.11 GB
rx-bytes   |            4.4 GB |           4.42 GB |           8.82 GB
-----      |                   |                   |
oerrors    |                 0 |                 0 |                 0
ierrors    |                 0 |                 0 |                 0

status:  /

browse:     'q' - quit, 'd' - dashboard, 'u' - util, 's' - streams, 'l' - latency,
dashboard:  'n' - reset view, 'o' - owned ports, 'a' - all ports, 'c' - clear,

**** mode == iptfs (imix new 50%/50%)

Global Statistics

connection   : localhost, Port 4501                       total_tx_L2  : 3.84 Gbps
version      : STL @ v2.98                                total_tx_L1  : 3.94 Gbps
cpu_util.    : 6.39% @ 2 cores (2 per dual port)          total_rx     : 2.9 Gbps
rx_cpu_util. : 6.74% / 0 pps                              total_pps    : 647.42 Kpps
async_util.  : 0% / 34.3 bps                              drop_rate    : 942.81 Mbps
total_cps.   : 0 cps                                      queue_full   : 0 pkts

Port Statistics

   port    |         0         |         1         |       total
-----------+-------------------+-------------------+------------------
owner      |              root |              root |
link       |                UP |                UP |
state      |      TRANSMITTING |      TRANSMITTING |
speed      |           40 Gb/s |           40 Gb/s |
CPU util.  |             6.39% |             6.39% |
--         |                   |                   |
Tx bps L2  |         1.92 Gbps |         1.92 Gbps |         3.84 Gbps
Tx bps L1  |         1.97 Gbps |         1.97 Gbps |         3.94 Gbps
Tx pps     |       323.87 Kpps |       324.12 Kpps |       647.99 Kpps
Line Util. |            4.93 % |            4.93 % |
---        |                   |                   |
Rx bps     |         1.45 Gbps |         1.45 Gbps |          2.9 Gbps
Rx pps     |       244.29 Kpps |       244.59 Kpps |       488.88 Kpps
----       |                   |                   |
opackets   |           6113860 |           6158922 |          12272782
ipackets   |           4643520 |           4678016 |           9321536
obytes     |        4530370260 |        4563761202 |        9094131462
ibytes     |        3440826656 |        3466377360 |        6907204016
tx-pkts    |        6.11 Mpkts |        6.16 Mpkts |       12.27 Mpkts
rx-pkts    |        4.64 Mpkts |        4.68 Mpkts |        9.32 Mpkts
tx-bytes   |           4.53 GB |           4.56 GB |           9.09 GB
rx-bytes   |           3.44 GB |           3.47 GB |           6.91 GB
-----      |                   |                   |
oerrors    |                 0 |                 0 |                 0
ierrors    |                 0 |                 0 |                 0

status:  /

browse:     'q' - quit, 'd' - dashboard, 'u' - util, 's' - streams, 'l' - latency,
dashboard:  'n' - reset view, 'o' - owned ports, 'a' - all ports, 'c' - clear,

**** mode == iptfs (imix legacy/firewall 7,4,1)
Global Statistics

connection   : localhost, Port 4501                       total_tx_L2  : 3.98 Gbps
version      : STL @ v2.98                                total_tx_L1  : 4.2 Gbps
cpu_util.    : 12.07% @ 2 cores (2 per dual port)         total_rx     : 2.02 Gbps
rx_cpu_util. : 9.33% / 0 pps                              total_pps    : 1.41 Mpps
async_util.  : 0% / 36.53 bps                             drop_rate    : 1.95 Gbps
total_cps.   : 0 cps                                      queue_full   : 0 pkts

Port Statistics

   port    |         0         |         1         |       total
-----------+-------------------+-------------------+------------------
owner      |              root |              root |
link       |                UP |                UP |
state      |      TRANSMITTING |      TRANSMITTING |
speed      |           40 Gb/s |           40 Gb/s |
CPU util.  |            12.07% |            12.07% |
--         |                   |                   |
Tx bps L2  |            2 Gbps |         1.98 Gbps |         3.98 Gbps
Tx bps L1  |         2.11 Gbps |         2.09 Gbps |          4.2 Gbps
Tx pps     |       706.35 Kpps |       700.51 Kpps |         1.41 Mpps
Line Util. |            5.28 % |            5.23 % |
---        |                   |                   |
Rx bps     |         1.02 Gbps |         1.01 Gbps |         2.02 Gbps
Rx pps     |       359.91 Kpps |       356.86 Kpps |       716.76 Kpps
----       |                   |                   |
opackets   |          10937602 |          10984861 |          21922463
ipackets   |           5620736 |           5645504 |          11266240
obytes     |        3866441526 |        3883148074 |        7749589600
ibytes     |        1985575700 |        1995323444 |        3980899144
tx-pkts    |       10.94 Mpkts |       10.98 Mpkts |       21.92 Mpkts
rx-pkts    |        5.62 Mpkts |        5.65 Mpkts |       11.27 Mpkts
tx-bytes   |           3.87 GB |           3.88 GB |           7.75 GB
rx-bytes   |           1.99 GB |              2 GB |           3.98 GB
-----      |                   |                   |
oerrors    |                 0 |                 0 |                 0
ierrors    |                 0 |                 0 |                 0

status:  \

browse:     'q' - quit, 'd' - dashboard, 'u' - util, 's' - streams, 'l' - latency,
dashboard:  'n' - reset view, 'o' - owned ports, 'a' - all ports, 'c' - clear,


**** mode == tunnel (i.e., normal ipsec) (imix legacy 7,4,1)
Global Statistics

connection   : localhost, Port 4501                       total_tx_L2  : 3.94 Gbps
version      : STL @ v2.98                                total_tx_L1  : 4.16 Gbps
cpu_util.    : 11.57% @ 2 cores (2 per dual port)         total_rx     : 1.5 Gbps
rx_cpu_util. : 8.49% / 0 pps                              total_pps    : 1.39 Mpps
async_util.  : 0% / 0 bps                                 drop_rate    : 2.43 Gbps
total_cps.   : 0 cps                                      queue_full   : 0 pkts

Port Statistics

   port    |         0         |         1         |       total
-----------+-------------------+-------------------+------------------
owner      |              root |              root |
link       |                UP |                UP |
state      |      TRANSMITTING |      TRANSMITTING |
speed      |           40 Gb/s |           40 Gb/s |
CPU util.  |            11.57% |            11.57% |
--         |                   |                   |
Tx bps L2  |         1.97 Gbps |         1.97 Gbps |         3.94 Gbps
Tx bps L1  |         2.08 Gbps |         2.08 Gbps |         4.16 Gbps
Tx pps     |       694.97 Kpps |       697.46 Kpps |         1.39 Mpps
Line Util. |            5.19 % |            5.21 % |
---        |                   |                   |
Rx bps     |       750.55 Mbps |       754.34 Mbps |          1.5 Gbps
Rx pps     |       265.62 Kpps |       266.53 Kpps |       532.14 Kpps
----       |                   |                   |
opackets   |         313742270 |         313798138 |         627540408
ipackets   |         120083200 |         120102542 |         240185742
obytes     |      110907888436 |      110927643186 |      221835531622
ibytes     |       42428351448 |       42428427258 |       84856778706
tx-pkts    |      313.74 Mpkts |       313.8 Mpkts |      627.54 Mpkts
rx-pkts    |      120.08 Mpkts |       120.1 Mpkts |      240.19 Mpkts
tx-bytes   |         110.91 GB |         110.93 GB |         221.84 GB
rx-bytes   |          42.43 GB |          42.43 GB |          84.86 GB
-----      |                   |                   |
oerrors    |                 0 |                 0 |                 0
ierrors    |                 0 |                 0 |                 0

status:  \

browse:     'q' - quit, 'd' - dashboard, 'u' - util, 's' - streams, 'l' - latency,
dashboard:  'n' - reset view, 'o' - owned ports, 'a' - all ports, 'c' - clear,

** These are 3 core
NOTE: for Qemu if multiple cores are used ipsec/iptfs seems to only use 1 thread
(core). If multple *sockets* are used then multiple threads (sockets) are utilized.
*** tests/stress/trex_stress_phy.py::test_policy_imix
**** New IMIX (50/50)
***** mode == tunnel (i.e., normal ipsec) (50%/50%)
===== 0 DROP May go faster =====

Global Statistics

connection   : localhost, Port 4501                       total_tx_L2  : 3.87 Gbps
version      : STL @ v2.98                                total_tx_L1  : 3.98 Gbps
cpu_util.    : 7.67% @ 2 cores (2 per dual port)          total_rx     : 3.87 Gbps
rx_cpu_util. : 10.18% / 0.12 pps                          total_pps    : 653.14 Kpps
async_util.  : 0% / 0 bps                                 drop_rate    : 0 bps
total_cps.   : 0 cps                                      queue_full   : 0 pkts

Port Statistics

   port    |         0         |         1         |       total
-----------+-------------------+-------------------+------------------
owner      |              root |              root |
link       |                UP |                UP |
state      |      TRANSMITTING |      TRANSMITTING |
speed      |           40 Gb/s |           40 Gb/s |
CPU util.  |             7.67% |             7.67% |
--         |                   |                   |
Tx bps L2  |         1.95 Gbps |         1.92 Gbps |         3.87 Gbps
Tx bps L1  |            2 Gbps |         1.97 Gbps |         3.98 Gbps
Tx pps     |       328.91 Kpps |       324.28 Kpps |       653.19 Kpps
Line Util. |            5.01 % |            4.94 % |
---        |                   |                   |
Rx bps     |         1.95 Gbps |         1.92 Gbps |         3.87 Gbps
Rx pps     |       328.91 Kpps |       324.25 Kpps |       653.16 Kpps
----       |                   |                   |
opackets   |          37006482 |          37035660 |          74042142
ipackets   |          37006464 |          37035618 |          74042082
obytes     |       27421803162 |       27443424060 |       54865227222
ibytes     |       27421789824 |       27443391520 |       54865181344
tx-pkts    |       37.01 Mpkts |       37.04 Mpkts |       74.04 Mpkts
rx-pkts    |       37.01 Mpkts |       37.04 Mpkts |       74.04 Mpkts
tx-bytes   |          27.42 GB |          27.44 GB |          54.87 GB
rx-bytes   |          27.42 GB |          27.44 GB |          54.87 GB
-----      |                   |                   |
oerrors    |                 0 |                 0 |                 0
ierrors    |                 0 |                 0 |                 0

status:  /

browse:     'q' - quit, 'd' - dashboard, 'u' - util, 's' - streams, 'l' - latency,
dashboard:  'n' - reset view, 'o' - owned ports, 'a' - all ports, 'c' - clear,
***** mode == iptfs (imix new 50%/50%)
Global Statistics

connection   : localhost, Port 4501                       total_tx_L2  : 3.85 Gbps
version      : STL @ v2.98                                total_tx_L1  : 3.95 Gbps
cpu_util.    : 6.35% @ 2 cores (2 per dual port)          total_rx     : 2.7 Gbps
rx_cpu_util. : 6.64% / 0 pps                              total_pps    : 649 Kpps
async_util.  : 0% / 33.17 bps                             drop_rate    : 1.14 Gbps
total_cps.   : 0 cps                                      queue_full   : 0 pkts

Port Statistics

   port    |         0         |         1         |       total
-----------+-------------------+-------------------+------------------
owner      |              root |              root |
link       |                UP |                UP |
state      |      TRANSMITTING |      TRANSMITTING |
speed      |           40 Gb/s |           40 Gb/s |
CPU util.  |             6.35% |             6.35% |
--         |                   |                   |
Tx bps L2  |         1.93 Gbps |         1.93 Gbps |         3.86 Gbps
Tx bps L1  |         1.98 Gbps |         1.99 Gbps |         3.97 Gbps
Tx pps     |       325.41 Kpps |       326.34 Kpps |       651.75 Kpps
Line Util. |            4.95 % |            4.97 % |
---        |                   |                   |
Rx bps     |         1.35 Gbps |         1.36 Gbps |         2.71 Gbps
Rx pps     |       228.17 Kpps |       228.88 Kpps |       457.05 Kpps
----       |                   |                   |
opackets   |           7075748 |           7094883 |          14170631
ipackets   |           5048896 |           5062638 |          10111534
obytes     |        5243129268 |        5257307626 |       10500436894
ibytes     |        3741435036 |        3751414630 |        7492849666
tx-pkts    |        7.08 Mpkts |        7.09 Mpkts |       14.17 Mpkts
rx-pkts    |        5.05 Mpkts |        5.06 Mpkts |       10.11 Mpkts
tx-bytes   |           5.24 GB |           5.26 GB |           10.5 GB
rx-bytes   |           3.74 GB |           3.75 GB |           7.49 GB
-----      |                   |                   |
oerrors    |                 0 |                 0 |                 0
ierrors    |                 0 |                 0 |                 0

status:  \

browse:     'q' - quit, 'd' - dashboard, 'u' - util, 's' - streams, 'l' - latency,
dashboard:  'n' - reset view, 'o' - owned ports, 'a' - all ports, 'c' - clear,

**** Old Imix 7,4,1
***** mode == iptfs (imix legacy/firewall 7,4,1)
Global Statistics

connection   : localhost, Port 4501                       total_tx_L2  : 3.93 Gbps
version      : STL @ v2.98                                total_tx_L1  : 4.16 Gbps
cpu_util.    : 14.76% @ 2 cores (2 per dual port)         total_rx     : 3.56 Gbps
rx_cpu_util. : 18.21% / 0 pps                             total_pps    : 1.39 Mpps
async_util.  : 0% / 30.14 bps                             drop_rate    : 0 bps
total_cps.   : 0 cps                                      queue_full   : 0 pkts

Port Statistics

   port    |         0         |         1         |       total
-----------+-------------------+-------------------+------------------
owner      |              root |              root |
link       |                UP |                UP |
state      |      TRANSMITTING |      TRANSMITTING |
speed      |           40 Gb/s |           40 Gb/s |
CPU util.  |            14.76% |            14.76% |
--         |                   |                   |
Tx bps L2  |         1.97 Gbps |         1.97 Gbps |         3.94 Gbps
Tx bps L1  |         2.08 Gbps |         2.09 Gbps |         4.17 Gbps
Tx pps     |       696.39 Kpps |       697.98 Kpps |         1.39 Mpps
Line Util. |             5.2 % |            5.21 % |
---        |                   |                   |
Rx bps     |         1.86 Gbps |         1.71 Gbps |         3.58 Gbps
Rx pps     |       658.15 Kpps |       606.26 Kpps |         1.26 Mpps
----       |                   |                   |
opackets   |          14995714 |          15099834 |          30095548
ipackets   |          14231296 |          13124265 |          27355561
obytes     |        5300982114 |        5337789222 |       10638771336
ibytes     |        5030619874 |        4638994972 |        9669614846
tx-pkts    |          15 Mpkts |        15.1 Mpkts |        30.1 Mpkts
rx-pkts    |       14.23 Mpkts |       13.12 Mpkts |       27.36 Mpkts
tx-bytes   |            5.3 GB |           5.34 GB |          10.64 GB
rx-bytes   |           5.03 GB |           4.64 GB |           9.67 GB
-----      |                   |                   |
oerrors    |                 0 |                 0 |                 0
ierrors    |                 0 |                 0 |                 0

status:  \

browse:     'q' - quit, 'd' - dashboard, 'u' - util, 's' - streams, 'l' - latency,
dashboard:  'n' - reset view, 'o' - owned ports, 'a' - all ports, 'c' - clear,
***** mode == tunnel (i.e., normal ipsec) (imix legacy 7,4,1)

Global Statistics

connection   : localhost, Port 4501                       total_tx_L2  : 3.95 Gbps
version      : STL @ v2.98                                total_tx_L1  : 4.17 Gbps
cpu_util.    : 10.12% @ 2 cores (2 per dual port)         total_rx     : 1.41 Gbps
rx_cpu_util. : 5.47% / 0 pps                              total_pps    : 1.4 Mpps
async_util.  : 0% / 34.58 bps                             drop_rate    : 2.54 Gbps
total_cps.   : 0 cps                                      queue_full   : 0 pkts

Port Statistics

   port    |         0         |         1         |       total
-----------+-------------------+-------------------+------------------
owner      |              root |              root |
link       |                UP |                UP |
state      |      TRANSMITTING |      TRANSMITTING |
speed      |           40 Gb/s |           40 Gb/s |
CPU util.  |            10.12% |            10.12% |
--         |                   |                   |
Tx bps L2  |         1.97 Gbps |         1.98 Gbps |         3.95 Gbps
Tx bps L1  |         2.08 Gbps |         2.09 Gbps |         4.17 Gbps
Tx pps     |       697.28 Kpps |       698.79 Kpps |          1.4 Mpps
Line Util. |            5.21 % |            5.22 % |
---        |                   |                   |
Rx bps     |       704.24 Mbps |       703.04 Mbps |         1.41 Gbps
Rx pps     |       247.81 Kpps |       248.36 Kpps |       496.17 Kpps
----       |                   |                   |
opackets   |          11321860 |          11419036 |          22740896
ipackets   |           4065024 |           4100397 |           8165421
obytes     |        4002278236 |        4036629952 |        8038908188
ibytes     |        1453675184 |        1455668512 |        2909343696
tx-pkts    |       11.32 Mpkts |       11.42 Mpkts |       22.74 Mpkts
rx-pkts    |        4.07 Mpkts |         4.1 Mpkts |        8.17 Mpkts
tx-bytes   |              4 GB |           4.04 GB |           8.04 GB
rx-bytes   |           1.45 GB |           1.46 GB |           2.91 GB
-----      |                   |                   |
oerrors    |                 0 |                 0 |                 0
ierrors    |                 0 |                 0 |                 0

status:  \

browse:     'q' - quit, 'd' - dashboard, 'u' - util, 's' - streams, 'l' - latency,
dashboard:  'n' - reset view, 'o' - owned ports, 'a' - all ports, 'c' - clear,


***** mode == iptfs (i.e., normal ipsec) 1G 40 octet packet
***** mode == tunnel (i.e., normal ipsec) 1G 40 octet packet
- tunnel 1G 40b pkt
- Global Statistics

connection   : localhost, Port 4501                       total_tx_L2  : 3 Gbps
version      : STL @ v2.98                                total_tx_L1  : 3.94 Gbps
cpu_util.    : 36.57% @ 2 cores (2 per dual port)         total_rx     : 494 Mbps
rx_cpu_util. : 13.65% / 0 pps                             total_pps    : 5.86 Mpps
async_util.  : 0% / 35.1 bps                              drop_rate    : 2.51 Gbps
total_cps.   : 0 cps                                      queue_full   : 0 pkts

Port Statistics

   port    |         0         |         1         |       total
-----------+-------------------+-------------------+------------------
owner      |              root |              root |
link       |                UP |                UP |
state      |      TRANSMITTING |      TRANSMITTING |
speed      |           40 Gb/s |           40 Gb/s |
CPU util.  |            36.57% |            36.57% |
--         |                   |                   |
Tx bps L2  |          1.5 Gbps |          1.5 Gbps |            3 Gbps
Tx bps L1  |         1.97 Gbps |         1.97 Gbps |         3.94 Gbps
Tx pps     |         2.93 Mpps |         2.93 Mpps |         5.86 Mpps
Line Util. |            4.93 % |            4.92 % |
---        |                   |                   |
Rx bps     |       250.51 Mbps |       243.49 Mbps |          494 Mbps
Rx pps     |       489.27 Kpps |       475.57 Kpps |       964.84 Kpps
----       |                   |                   |
opackets   |          89007203 |          89443956 |         178451159
ipackets   |          14835660 |          14522048 |          29357708
obytes     |        5696460992 |        5724413184 |       11420874176
ibytes     |         949482112 |         929411072 |        1878893184
tx-pkts    |       89.01 Mpkts |       89.44 Mpkts |      178.45 Mpkts
rx-pkts    |       14.84 Mpkts |       14.52 Mpkts |       29.36 Mpkts
tx-bytes   |            5.7 GB |           5.72 GB |          11.42 GB
rx-bytes   |         949.48 MB |         929.41 MB |           1.88 GB
-----      |                   |                   |
oerrors    |                 0 |                 0 |                 0
ierrors    |                 0 |                 0 |                 0

status:  |

browse:     'q' - quit, 'd' - dashboard, 'u' - util, 's' - streams, 'l' - latency,
dashboard:  'n' - reset view, 'o' - owned ports, 'a' - all ports, 'c' - clear,

